server:
  port: 8081

spring:
  application:
    name: Circuit-Breaker

management:
  endpoints:
         web:
          exposure:
            include: '*'
  endpoint:
      health:
        show-details: always
  health:
      circuitbreaker:
        enabled: true

resilience4j.circuitbreaker:
    instances:
      payment-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 100s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
