server:
  port: 7071
spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
          git:
            uri: https://github.com/jkumarda/config-server-repo.git
            clone-on-start: true